name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build the protobuf
      run: ruby build_proto.rb
    - name: Build
      run: dotnet build
    - name: Test
      run: dotnet test --no-build --verbosity normal
